VAPID_PUBLIC_KEY = "BGRkZKFkcea3gDJqTW7yD8Kz-6UiVsWF09kGpd2G2jjjxaXtqvL1pwMalR1LHDqIRIWfkh84zSKRuYkfoWLwfh4"
VAPID_PRIVATE_KEY = "ZVY_ZZbrfil_WiuloVxXG-93y3MaXZUDTEZm_IdYLB4"
VAPID_CLAIM_EMAIL = "[email protected]"
